
# site details
name: Open Pencil
url: ../
baseurl: /bayesianmice
description: Bayesian modeling for C. albicans colonization.
avatar: https://avatars3.githubusercontent.com/u/1999668?v=2&s=70

# Conversion
markdown: kramdown
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
    - generate_toc
  toc_token: "!TOC"
highlighter: pygments

email: jyoti.shankar@icloud.com
github: openpencil
